# Generated by Django 5.2 on 2025-05-25 15:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_numeric', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_interval', models.IntegerField(verbose_name='Длительность (дни)')),
                ('start_location', models.CharField(max_length=255, verbose_name='Место начала')),
                ('end_location', models.CharField(max_length=255, verbose_name='Место окончания')),
                ('max_participants', models.IntegerField(verbose_name='Максимум участников')),
                ('available_dates', models.DateField(verbose_name='Дата проведения')),
                ('status', models.CharField(default='Доступен', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['-available_dates'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('role', models.CharField(default='Гость', max_length=50, verbose_name='Роль')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='TourUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='Участник', max_length=50, verbose_name='Роль')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecotourism.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecotourism.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник тура',
                'verbose_name_plural': 'Участники туров',
                'ordering': ['tour'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecotourism.user', verbose_name='Кем создан'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecotourism.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecotourism.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecotourism.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecotourism.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата бронирования')),
                ('participant_count', models.IntegerField(verbose_name='Количество участников')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('status', models.CharField(default='Ожидает', max_length=50, verbose_name='Статус')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecotourism.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecotourism.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-booking_date'],
            },
        ),
    ]
